### ISSUE TITLE
Additional music data "types"

### ISSUE THREAD

**Issue by vibertthio** [affige/DeepMIR#1]
Hi @affige ,

Thanks for publishing the materials of this amazing class!

Besides 1. music “audio” data 2. music “listening” data and 3. big music “text” data, I think there are 2 additional interesting data about music to be explored:

1. Music video data (how music is correlated to visual data)
2. Music editing data (how music is made, changed, edited by a human or an algorithm)

**Comment by affige** [comment]
Agreed!  Would revise later.  Thanks for the suggestions!
